apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-components
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/cyb3rflx/homelab.git
    targetRevision: HEAD
    path: ./manifests/infrastructure
  destination:
    server: https://kubernetes.default.svc
    namespace: infrastructure
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
